export const IMAGES = {
  pay: require("./images/pay.png"),
  password: require("./images/password.png"),
  facebook: require("./images/facebook.png"),
  google: require("./images/google.png"),
  apple: require("./images/apple.png"),
  dollard: require("./images/dollard.png"),
  confirm: require("./images/confirm.png"),
  defaultProfile: require("./images/profile.jpg"),
  visa: require("./images/visa.png"),
  mastercard: require("./images/mastercard.png"),
  send: require("./images/send.png"),
  exchange: require("./images/exchange.png"),
  download: require("./images/download.png"),
  flash: require("./images/flash.png"),
  wifi: require("./images/wifi.png"),
  drop: require("./images/drop.png"),
  suitcase: require("./images/suitcase.png"),
  card: require("./images/card.png"),
  cart: require("./images/cart.png"),
  chart: require("./images/chart.png"),
  health: require("./images/health.png"),
  phone: require("./images/phone.png"),
  shop: require("./images/shop.png"),
  tv: require("./images/tv.png"),
  percent: require("./images/percent.png"),
};
